services:
  - type: web
    name: mca-analysis-service
    repo: https://github.com/j-low/mca-analysis-handler
    branch: master
    runtime: docker        # Use your Dockerfile (Python 3.11 base image)
    autoDeploy: true
    plan: starter
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: BEA_API_KEY
        sync: false
      - key: FRED_API_KEY
        sync: false
      - key: BLS_API_KEY
        sync: false
